// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQxyoTLOj8JGTR_EYDPsdSr2DLROeGM_A',
    appId: '1:195458795469:android:bd6a2d45ad4a8f2ab46684',
    messagingSenderId: '195458795469',
    projectId: 'nyaa-f175d',
    storageBucket: 'nyaa-f175d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcCwVg9AqhNtQ2NCt9dwkNEkRApwTilH4',
    appId: '1:195458795469:ios:50fe1fc3dfa0b0f2b46684',
    messagingSenderId: '195458795469',
    projectId: 'nyaa-f175d',
    storageBucket: 'nyaa-f175d.appspot.com',
    androidClientId: '195458795469-d97m5i4sck3qm06c996gul1ele07j3rv.apps.googleusercontent.com',
    iosClientId: '195458795469-hee70f455fh12d1q6o86n2a5em40qf8j.apps.googleusercontent.com',
    iosBundleId: 'com.catto.nyaa',
  );
}
